const BLOG_POST = {
    scribeSize: "📜 Scribe Size:",
    decreaseSize: "Decrease text size",
    increaseSize: "Increase text size",
    bookmarkAdd: "🔖 Bookmark Scroll",
    bookmarkRemove: "🔖 Bookmarked",
    clickToEnlarge: "Click to enlarge",
    aboutScribe: "About the Scribe",
    authorName: "Mouad ALLAOUI",
    authorRole: "Full-Stack Developer & Cybersecurity Scholar",
    authorBio: "Exploring the realms of front-end mechanics, back-end architecture, and digital security.",
    scrollMap: "Scroll Map",
    chronicleDetails: "Chronicle Details",
    penned: "Penned:",
    reading: "Reading:",
    length: "Length:",
    category: "Category:",
    lore: "Lore",
    words: "words",
    shareTitle: "Share Chronicle",
    twitter: "Twitter",
    linkedin: "LinkedIn",
    facebook: "Facebook",
    qrCode: "QR Code",
    copyUrl: "Copy URL",
    shareOnTwitter: "Share on Twitter",
    shareOnLinkedIn: "Share on LinkedIn",
    shareOnFacebook: "Share on Facebook",
    showQrCode: "Show QR Code",
    copyLink: "Copy Link",
    grimoireLibrary: "Grimoire Library",
    scanScroll: "Scan Scroll",
    shareScroll: "Share on {{platform}}",
    checkScroll: "Check out this scroll!",
    scrollStats: "Reading Progress",
    wordsRead: "words read",
    timeLeft: "min left",
    tableOfContents: "Table of Contents",
    relatedPosts: "You Might Also Like",
}

export { BLOG_POST }
