const PROJECTS_PAGE = {
    title: "Tech Quests",
    subtitle: "A collection of applications, systems, and technical work.",
    searchPlaceholder: "Search quests...",
    filterAll: "All Tags",
    noResults: "No quests match your search",
    featuredQuests: "⭐ Featured Quests",
    clearFilters: "Clear Filters",
    quests: "quest",
    questsPlural: "quests",
    found: "found",
    viewQuest: "View Quest",
    viewCode: "View Code",
    liveDemo: "Live Demo",
    backToProjects: "Back to Quests",
    notFoundTitle: "Quest Registry Missing",
    notFoundText: "This chronicle has not been penned yet or was lost in the archives.",
    clickToEnlarge: "Inspect Relic",
    questYear: "Penciled in",
    specSheet: "Quest Specification",
    statusLabel: "Quest Status",
    categoryLabel: "Classification",
    relics: "Enchanted Relics",
    questOverview: "Quest Overview",
    detailedChronicle: "Detailed Chronicle",
    prevQuest: "Previous Quest",
    nextQuest: "Next Quest",
    allQuests: "All Quests",
    technologies: "Technologies Used",
    role: "Role",
    details: "Project Details",
    siteLink: "Visit Website",
    codeLink: "View Source Code",
    unknown: "Unknown Date",
    categories: {
        web: "Web Citadels",
        app: "Mobile & Desktop Relics",
        tool: "Alchemical Tools",
    },
    status: {
        completed: "Completed",
        "in-progress": "In Progress",
        archived: "Archived",
    },
}

export { PROJECTS_PAGE }
