const BLOG_POST = {
    scribeSize: "📜 Taille du Scribe :",
    decreaseSize: "Réduire la taille du texte",
    increaseSize: "Augmenter la taille du texte",
    bookmarkAdd: "🔖 Ajouter aux favoris",
    bookmarkRemove: "🔖 Favorisé",
    clickToEnlarge: "Cliquez pour agrandir",
    aboutScribe: "À propos du Scribe",
    authorName: "Mouad ALLAOUI",
    authorRole: "Développeur Full-Stack & Étudiant en Cybersécurité",
    authorBio: "Explorer les domaines du frontend, de l'architecture backend et de la sécurité numérique.",
    scrollMap: "Carte du Parchemin",
    chronicleDetails: "Détails de la Chronique",
    penned: "Rédigé :",
    reading: "Lecture :",
    length: "Longueur :",
    category: "Catégorie :",
    lore: "Histoire",
    words: "mots",
    shareTitle: "Partager la Chronique",
    twitter: "Twitter",
    linkedin: "LinkedIn",
    facebook: "Facebook",
    qrCode: "Code QR",
    copyUrl: "Copier l'URL",
    shareOnTwitter: "Partager sur Twitter",
    shareOnLinkedIn: "Partager sur LinkedIn",
    shareOnFacebook: "Partager sur Facebook",
    showQrCode: "Afficher le code QR",
    copyLink: "Copier le lien",
    grimoireLibrary: "Bibliothèque du Grimoire",
    scanScroll: "Scanner le Parchemin",
    shareScroll: "Partager sur {{platform}}",
    checkScroll: "Découvrez ce parchemin !",
    scrollStats: "Progression de Lecture",
    wordsRead: "mots lus",
    timeLeft: "min restantes",
    tableOfContents: "Table des Matières",
    relatedPosts: "Vous Aimerez Aussi",
}

export { BLOG_POST }
