const PROJECTS_PAGE = {
    title: "Quêtes Techniques",
    subtitle: "Une collection d'applications, de systèmes et de travaux techniques.",
    searchPlaceholder: "Rechercher des quêtes...",
    filterAll: "Toutes les Balises",
    noResults: "Aucune quête ne correspond à votre recherche",
    featuredQuests: "⭐ Quêtes en Vedette",
    clearFilters: "Effacer les Filtres",
    quests: "quête",
    questsPlural: "quêtes",
    found: "trouvé",
    viewQuest: "Voir la Quête",
    viewCode: "Voir le Code",
    liveDemo: "Démo en Direct",
    backToProjects: "Retour aux Quêtes",
    notFoundTitle: "Registre de Quêtes Introuvable",
    notFoundText: "Cette chronique n'a pas encore été rédigée ou a été perdue dans les archives.",
    clickToEnlarge: "Inspecter l'Artéfact",
    questYear: "Inscrit en",
    specSheet: "Spécifications de la Quête",
    statusLabel: "Statut de la Quête",
    categoryLabel: "Classification",
    relics: "Reliques Enchantées",
    questOverview: "Aperçu de la Quête",
    detailedChronicle: "Chronique Détaillée",
    prevQuest: "Quête Précédente",
    nextQuest: "Quête Suivante",
    allQuests: "Toutes les Quêtes",
    technologies: "Technologies Utilisées",
    role: "Rôle",
    details: "Détails du Projet",
    siteLink: "Visiter le Site",
    codeLink: "Voir le Code Source",
    unknown: "Date Inconnue",
    categories: {
        web: "Citadelles Web",
        app: "Reliques Bureau & Mobiles",
        tool: "Outils Alchimiques",
    },
    status: {
        completed: "Achevée",
        "in-progress": "En Cours",
        archived: "Archivée",
    },
}

export { PROJECTS_PAGE }
