const BLOG_POST = {
    scribeSize: "📜 Scribe Size:",
    decreaseSize: "Shrink the runes",
    increaseSize: "Enlarge the runes",
    bookmarkAdd: "🔖 Mark this Scroll",
    bookmarkRemove: "🔖 Scroll Marked",
    clickToEnlarge: "Inspect the vision",
    aboutScribe: "About the Scribe",
    authorName: "Mouad ALLAOUI",
    authorRole: "Full-Stack Developer & Cybersecurity Scholar",
    authorBio: "Exploring the realms of front-end mechanics, back-end architecture, and digital security.",
    scrollMap: "Map of the Scroll",
    chronicleDetails: "Chronicle Details",
    penned: "Penned:",
    reading: "Reading:",
    length: "Length:",
    category: "Classification:",
    lore: "Lore",
    words: "words",
    shareTitle: "Share Chronicle",
    twitter: "Twitter",
    linkedin: "LinkedIn",
    facebook: "Facebook",
    qrCode: "Rune Code",
    copyUrl: "Transcribe URL",
    shareOnTwitter: "Share on Twitter",
    shareOnLinkedIn: "Share on LinkedIn",
    shareOnFacebook: "Share on Facebook",
    showQrCode: "Reveal Rune Code",
    copyLink: "Transcribe Link",
    grimoireLibrary: "Grimoire Library",
    scanScroll: "Scan the Scroll",
    shareScroll: "Share on {{platform}}",
    checkScroll: "Behold this scroll!",
    scrollStats: "Scroll of Progress",
    wordsRead: "words unfurled",
    timeLeft: "minutes remaining",
    tableOfContents: "Map of Scroll",
    relatedPosts: "Thou Mayest Also Enjoy",
}

export { BLOG_POST }
