const PROJECTS_PAGE = {
    title: "Tech Quests",
    subtitle: "Legendary quests and enchanted artifacts",
    searchPlaceholder: "Search quests...",
    filterAll: "All Markings",
    noResults: "No quests match thy search",
    featuredQuests: "⭐ Featured Quests",
    clearFilters: "Clear Enchantments",
    quests: "quest",
    questsPlural: "quests",
    found: "found",
    viewQuest: "View Quest",
    viewCode: "View Rune Code",
    liveDemo: "Scry Live Demo",
    backToProjects: "Return to Quests",
    notFoundTitle: "Quest Registry Missing",
    notFoundText: "This chronicle has not been penned yet or was lost in the archives.",
    clickToEnlarge: "Inspect Relic",
    questYear: "Penciled in",
    specSheet: "Quest Specification",
    statusLabel: "Quest Status",
    categoryLabel: "Classification",
    relics: "Enchanted Relics",
    questOverview: "Quest Overview",
    detailedChronicle: "Detailed Chronicle",
    prevQuest: "Previous Quest",
    nextQuest: "Next Quest",
    allQuests: "All Quests",
    technologies: "Enchanted Runes",
    role: "Role",
    details: "Chronicle Details",
    siteLink: "Visit the Realm",
    codeLink: "View Source Runes",
    unknown: "Unknown Date",
    categories: {
        web: "Web Citadels",
        app: "Mobile & Desktop Relics",
        tool: "Alchemical Tools",
    },
    status: {
        completed: "Achev'd",
        "in-progress": "In Progress",
        archived: "Archiv'd",
    },
}

export { PROJECTS_PAGE }
