const BLOG_POST = {
    scribeSize: "📜 Taille du Scribe :",
    decreaseSize: "Rétrécir les runes",
    increaseSize: "Agrandir les runes",
    bookmarkAdd: "🔖 Marquer ce Parchemin",
    bookmarkRemove: "🔖 Parchemin Marqué",
    clickToEnlarge: "Inspecter la vision",
    aboutScribe: "À propos du Scribe",
    authorName: "Mouad ALLAOUI",
    authorRole: "Développeur Full-Stack & Étudiant en Cybersécurité",
    authorBio: "Explorer les domaines du frontend, de l'architecture backend et de la sécurité numérique.",
    scrollMap: "Carte du Parchemin",
    chronicleDetails: "Détails de la Chronique",
    penned: "Griffonné :",
    reading: "Lecture :",
    length: "Longueur :",
    category: "Classification :",
    lore: "Lore",
    words: "mots",
    shareTitle: "Partager la Chronique",
    twitter: "Twitter",
    linkedin: "LinkedIn",
    facebook: "Facebook",
    qrCode: "Code Runique",
    copyUrl: "Transcrire l'URL",
    shareOnTwitter: "Partager sur Twitter",
    shareOnLinkedIn: "Partager sur LinkedIn",
    shareOnFacebook: "Partager sur Facebook",
    showQrCode: "Révéler le Code Runique",
    copyLink: "Transcrire le Lien",
    grimoireLibrary: "Bibliothèque du Grimoire",
    scanScroll: "Scanner le Parchemin",
    shareScroll: "Partager sur {{platform}}",
    checkScroll: "Contemple ce parchemin !",
    scrollStats: "Progression du Parchemin",
    wordsRead: "mots déchiffrés",
    timeLeft: "sabliers restants",
    tableOfContents: "Carte du Parchemin",
    relatedPosts: "Tu Pourrais Aussi Apprécier",
}

export { BLOG_POST }
