const PROJECTS_PAGE = {
    title: "Hauts Faits",
    subtitle: "Quêtes légendaires et reliques enchantées",
    searchPlaceholder: "Rechercher des exploits...",
    filterAll: "Tous les Sceaux",
    noResults: "Nul exploit ne correspond",
    featuredQuests: "⭐ Quêtes en Vedette",
    clearFilters: "Effacer les Enchantements",
    quests: "exploit",
    questsPlural: "exploits",
    found: "trouvé",
    viewQuest: "Inspecter l'Exploit",
    viewCode: "Examiner les Runes",
    liveDemo: "Observer la Vision",
    backToProjects: "Retourner aux Quêtes",
    notFoundTitle: "Registre de Quêtes Introuvable",
    notFoundText: "Cette chronique n'a pas encore été rédigée ou a été perdue dans les archives.",
    clickToEnlarge: "Inspecter la Relique",
    questYear: "Inscrit en l'an",
    specSheet: "Spécifications de la Quête",
    statusLabel: "Statut de la Quête",
    categoryLabel: "Classification",
    relics: "Reliques Enchantées",
    questOverview: "Aperçu de la Quête",
    detailedChronicle: "Chronique Détaillée",
    prevQuest: "Quête Précédente",
    nextQuest: "Quête Suivante",
    allQuests: "Toutes les Quêtes",
    technologies: "Runes Enchantées",
    role: "Rôle",
    details: "Détails de la Chronique",
    siteLink: "Visiter le Royaume",
    codeLink: "Voir les Runes Sources",
    unknown: "Date Inconnue",
    categories: {
        web: "Citadelles Web",
        app: "Reliques Mobiles & Bureau",
        tool: "Outils Alchimiques",
    },
    status: {
        completed: "Achevée",
        "in-progress": "En Cours",
        archived: "Archivée",
    },
}

export { PROJECTS_PAGE }
