const BLOG_POST = {
    scribeSize: "📜 حجم الخط:",
    decreaseSize: "تصغير حجم النص",
    increaseSize: "تكبير حجم النص",
    bookmarkAdd: "🔖 إضافة للمفضلة",
    bookmarkRemove: "🔖 مفضل",
    clickToEnlarge: "انقر للتكبير",
    aboutScribe: "عن الكاتب",
    authorName: "مؤاد علاوي",
    authorRole: "مطور ويب وطالب أمن سيبراني",
    authorBio: "استكشاف مجالات الواجهة الأمامية وهندسة الخلفية والأمن الرقمي.",
    scrollMap: "خريطة المخطوطة",
    chronicleDetails: "تفاصيل السجل",
    penned: "كتبت في:",
    reading: "القراءة:",
    length: "الطول:",
    category: "الفئة:",
    lore: "الأسطورة",
    words: "كلمات",
    shareTitle: "مشاركة السجل",
    twitter: "تويتر",
    linkedin: "لينكدإن",
    facebook: "فيسبوك",
    qrCode: "رمز QR",
    copyUrl: "نسخ الرابط",
    shareOnTwitter: "مشاركة على تويتر",
    shareOnLinkedIn: "مشاركة على لينكدإن",
    shareOnFacebook: "مشاركة على فيسبوك",
    showQrCode: "إظهار رمز QR",
    copyLink: "نسخ الرابط",
    grimoireLibrary: "مكتبة الكتاب",
    scanScroll: "مسح المخطوطة",
    shareScroll: "مشاركة على {{platform}}",
    checkScroll: "تحقق من هذه المخطوطة!",
    scrollStats: "تقدم القراءة",
    wordsRead: "كلمة مقروءة",
    timeLeft: "دقائق متبقية",
    tableOfContents: "فهرس المحتوى",
    relatedPosts: "قد يعجبك أيضاً",
}

export { BLOG_POST }
