const PROJECTS_PAGE = {
    title: "المهام التقنية",
    subtitle: "مجموعة من التطبيقات والأنظمة والعمل التقني.",
    searchPlaceholder: "البحث عن المهام...",
    filterAll: "كل الوسوم",
    noResults: "لا توجد مهام تطابق بحثك",
    featuredQuests: "⭐ المهام المميزة",
    clearFilters: "مسح الفلاتر",
    quests: "مهمة",
    questsPlural: "مهام",
    found: "وجدت",
    viewQuest: "عرض المهمة",
    viewCode: "عرض الكود",
    liveDemo: "البث الحي",
    backToProjects: "العودة للمهام",
    notFoundTitle: "سجل المهمة مفقود",
    notFoundText: "هذا السجل لم يُكتب بعد أو فُقد في الأرشيف.",
    clickToEnlarge: "فحص القطعة الأثرية",
    questYear: "كُتبت في عام",
    specSheet: "مواصفات المهمة",
    statusLabel: "حالة المهمة",
    categoryLabel: "التصنيف",
    relics: "القطع الأثرية المسحورة",
    questOverview: "نظرة عامة على المهمة",
    detailedChronicle: "التفاصيل الكاملة للمهمة",
    prevQuest: "المهمة السابقة",
    nextQuest: "المهمة التالية",
    allQuests: "كل المهام",
    technologies: "التقنيات المستخدمة",
    role: "الدور",
    details: "تفاصيل المشروع",
    siteLink: "زيارة الموقع",
    codeLink: "عرض الكود المصدري",
    unknown: "تاريخ غير معروف",
    categories: {
        web: "حصون الويب",
        app: "آثار الهاتف والمكتب",
        tool: "أدوات الخيمياء",
    },
    status: {
        completed: "مكتملة",
        "in-progress": "قيد التنفيذ",
        archived: "مؤرشفة",
    },
}

export { PROJECTS_PAGE }
