/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      screens: {
        xs: '360px',
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1280px',
        '2xl': '1536px',
      },
      fontFamily: {
        cinzel: ['Cinzel', 'serif'],
        fell: ['"IM Fell English SC"', 'serif'],
        medieval: ['MedievalSharp', 'cursive'],
        body: ['Lora', 'serif'],
      },
      colors: {
        parchment: '#f5e6ca',
        'parchment-dark': '#e8d5b0',
        'parchment-dark-alpha': '#e8d5b08e',
        gold: '#d4af37',
        'gold-light': '#f0c75e',
        brown: '#8b4513',
        'dark-brown': '#3a2921',
        'dark-gray': '#242424',
        torchlight: '#ff9d00',
        'magic-blue': '#1e90ff',
        'magic-purple': '#9370db',
        rust: '#8c3a2b',
        'rust-light': '#b05a46',
        forest: '#2c5e1a',
        'forest-2': '#4f9336',
        'purple-glow': '#8a2be2',
        'stone-dark': '#2c2416',
        'stone-medium': '#4a3c28',
        'stone-light': '#6b5b47',
        copper: '#b87333',
        iron: '#71797e',
        crimson: '#8b1538',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeInScroll: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        fadeOutScroll: { '0%': { opacity: '1', transform: 'translateY(0)' }, '100%': { opacity: '0', transform: 'translateY(20px)' } },
        flyAway: {
          '0%': { transform: 'translate(0, 0) scale(1) rotate(0deg)', opacity: '1' },
          '30%': { transform: 'translate(50vw, -100px) scale(1.2) rotate(-5deg)', opacity: '0.9' },
          '100%': { transform: 'translate(100vw, -100vh) scale(0.2) rotate(-20deg)', opacity: '0' },
        },
        glowingBorder: {
          '0%': { backgroundPosition: '0% 50%', filter: 'blur(5px)' },
          '50%': { backgroundPosition: '100% 50%', filter: 'blur(8px)' },
          '100%': { backgroundPosition: '0% 50%', filter: 'blur(5px)' },
        },
        borderGlow: {
          '0%': { boxShadow: '0 0 5px #9370db', left: '0', width: '100%', height: '1px' },
          '100%': { boxShadow: '0 0 15px #8a2be2', left: '40%', width: '20%', height: '3px' },
        },
        titleFloat: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-10px)' } },
        particleRotate: { '0%': { transform: 'rotate(0deg)' }, '100%': { transform: 'rotate(360deg)' } },
        spinnerRotate: { '0%': { transform: 'translateY(0%) rotate(0deg)' }, '50%': { transform: 'translateY(-20%) rotate(180deg)' }, '100%': { transform: 'translateY(0%) rotate(360deg)' } },
        crystalGlow: { '0%': { boxShadow: '0 0 20px rgba(147,112,219,.6), inset 0 0 20px rgba(255,255,255,.5)' }, '50%': { boxShadow: '0 0 30px rgba(30,144,255,.8), inset 0 0 30px rgba(255,255,255,.7)' }, '100%': { boxShadow: '0 0 20px rgba(147,112,219,.6), inset 0 0 20px rgba(255,255,255,.5)' } },
        crystalFloat: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-15px)' } },
        fadeInUp: { '0%': { opacity: '0', transform: 'translateY(20px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        unrollMessage: { '0%': { transform: 'scaleY(0)', opacity: '0' }, '100%': { transform: 'scaleY(1)', opacity: '1' } },
        fadeInRight: { '0%': { opacity: '0', transform: 'translateX(90px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        frameFloat: { '0%,100%': { transform: 'translateY(0) rotate(0deg)' }, '50%': { transform: 'translateY(-8px) rotate(1deg)' } },
        wizardGlow: { '0%': { filter: 'brightness(1)' }, '100%': { filter: 'brightness(1.15)' } },
        unrollScroll: { '0%': { transform: 'scaleY(0)', opacity: '0' }, '100%': { transform: 'scaleY(1)', opacity: '1' } },
        quillFloat: { '0%,100%': { transform: 'translateY(0) rotate(-3deg)' }, '50%': { transform: 'translateY(-6px) rotate(3deg)' } },
        titleGlow: { '0%,100%': { textShadow: '0 0 8px rgba(212,175,55,.5)' }, '50%': { textShadow: '0 0 16px rgba(212,175,55,.9)' } },
        pulse: { '0%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.05)' }, '100%': { transform: 'scale(1)' } },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'slide-down': {
          '0%': { opacity: '1', transform: 'translateY(0)' },
          '100%': { opacity: '0', transform: 'translateY(20px)' },
        },
        'rotate-in': {
          '0%': { opacity: '0', transform: 'rotate(-5deg) scale(0.95)' },
          '100%': { opacity: '1', transform: 'rotate(0deg) scale(1)' },
        },
      },
      animation: {
        fadeIn: 'fadeIn .6s ease-out',
        fadeInScroll: 'fadeInScroll .6s ease-out',
        fadeOutScroll: 'fadeOutScroll .6s ease-out',
        flyAway: 'flyAway 1.6s ease-in forwards',
        glowingBorder: 'glowingBorder 10s ease infinite',
        borderGlow: 'borderGlow 4s ease-in-out infinite',
        titleFloat: 'titleFloat 4s ease-in-out infinite',
        particleRotate: 'particleRotate 10s linear infinite',
        spinnerRotate: 'spinnerRotate 1.2s linear infinite',
        crystalGlow: 'crystalGlow 5s infinite alternate',
        crystalFloat: 'crystalFloat 6s ease-in-out infinite',
        fadeInUp: 'fadeInUp .6s ease-out',
        unrollMessage: 'unrollMessage .5s ease-out',
        fadeInRight: 'fadeInRight .6s ease-out',
        frameFloat: 'frameFloat 5s ease-in-out infinite',
        wizardGlow: 'wizardGlow 3s infinite alternate',
        unrollScroll: 'unrollScroll 1.5s ease-out',
        quillFloat: 'quillFloat 4s ease-in-out infinite',
        titleGlow: 'titleGlow 2.5s ease-in-out infinite',
        pulse: 'pulse 2s ease-in-out infinite',
        'fade-in': 'fade-in 0.3s ease-out forwards',
        'slide-up': 'slide-up 0.4s ease-out forwards',
        'scale-in': 'scale-in 0.3s ease-out forwards',
        'slide-down': 'slide-down 0.3s ease-in forwards',
        'rotate-in': 'rotate-in 0.3s ease-out forwards',
      },
      cursor: {
        friend: "url('/assets/cursor/WenrexaAssetsMagicCursorsPack/36x36px/Cursor Default Friends.png'), auto",
        enemy: "url('/assets/cursor/WenrexaAssetsMagicCursorsPack/36x36px/Cursor Default Enemy.png'), auto",
        'magic-blue': "url('/assets/cursor/WenrexaAssetsMagicCursorsPack/36x36px/Cursor Magic Use Blue.png'), auto",
      },
    },
  },
  plugins: [],
};
