/**
 * Achievements Registry
 *
 * To add a new achievement:
 * 1. Add one entry here
 * 2. Call unlockAchievement(id) anywhere in the app
 * 3. Done — it appears automatically everywhere
 *
 * Rarity tiers:
 * - common    — easy to get, most visitors will unlock
 * - uncommon  — requires some exploration
 * - rare      — requires specific actions
 * - epic      — requires dedication
 * - legendary — hidden, unexpected, very hard
 */

export const ACHIEVEMENTS = {

  // ── Explorer ─────────────────────────────────────────────────
  first_visit: {
    id: 'first_visit',
    title: 'First Steps into the Keep',
    titleMedievalEn: 'The Gates Have Opened',
    description: 'Visited the portfolio for the first time',
    descMedievalEn: 'Thou hast crossed the threshold of the enchanted keep',
    icon: '🏰',
    rarity: 'common',
    category: 'explorer',
    secret: false,
    xp: 10,
  },

  visited_blogs: {
    id: 'visited_blogs',
    title: 'The Scribe\'s Apprentice',
    titleMedievalEn: 'Seeker of the Written Word',
    description: 'Visited the blogs section',
    descMedievalEn: 'Thou hast entered the Chamber of Arcane Writings',
    icon: '📜',
    rarity: 'common',
    category: 'explorer',
    secret: false,
    xp: 15,
  },

  visited_crmef: {
    id: 'visited_crmef',
    title: 'The Academic Path',
    titleMedievalEn: 'Scholar of the Order',
    description: 'Visited the CRMEF portal',
    descMedievalEn: 'Thou hast studied within the halls of the Order',
    icon: '🎓',
    rarity: 'uncommon',
    category: 'explorer',
    secret: false,
    xp: 20,
  },

  visited_all_sections: {
    id: 'visited_all_sections',
    title: 'Grand Tour',
    titleMedievalEn: 'Wanderer of the Keep',
    description: 'Scrolled through all sections on the home page',
    descMedievalEn: 'Thou hast explored every chamber of the enchanted keep',
    icon: '🗺️',
    rarity: 'uncommon',
    category: 'explorer',
    secret: false,
    xp: 30,
  },

  visited_settings: {
    id: 'visited_settings',
    title: 'The Configurator',
    titleMedievalEn: 'Master of the Arcane Grimoire',
    description: 'Opened the settings page',
    descMedievalEn: 'Thou hast consulted the Arcane Settings Grimoire',
    icon: '⚙️',
    rarity: 'common',
    category: 'explorer',
    secret: false,
    xp: 10,
  },

  visited_projects: {
    id: 'visited_projects',
    title: 'The Artificer',
    titleMedievalEn: 'Warden of the Armory',
    description: 'Visited the projects section',
    descMedievalEn: 'Thou hast entered the Armory of Grand Constructions',
    icon: '🔨',
    rarity: 'common',
    category: 'explorer',
    secret: false,
    xp: 15,
  },

  visited_skills: {
    id: 'visited_skills',
    title: 'The Apprentice',
    titleMedievalEn: 'Seeker of the Skill Tomes',
    description: 'Visited the skills section',
    descMedievalEn: 'Thou hast opened the Forbidden Tomes of Skill',
    icon: '⚔️',
    rarity: 'common',
    category: 'explorer',
    secret: false,
    xp: 15,
  },

  portfolio_completionist: {
    id: 'portfolio_completionist',
    title: 'Portfolio Completionist',
    titleMedievalEn: 'Master Cartographer',
    description: 'Visited every page and section in the portfolio',
    descMedievalEn: 'Thou hast charted every corner of the enchanted realm',
    icon: '🗺️',
    rarity: 'epic',
    category: 'explorer',
    secret: false,
    xp: 150,
  },

  deep_diver: {
    id: 'deep_diver',
    title: 'Deep Diver',
    titleMedievalEn: 'Delver of the Deep',
    description: 'Scrolled to the very bottom of 3 different pages',
    descMedievalEn: 'Thou hast plumbed the deepest depths of three chambers',
    icon: '🤿',
    rarity: 'rare',
    category: 'explorer',
    secret: false,
    xp: 50,
    requirement: { type: 'count', key: 'pages_scrolled_bottom', target: 3 },
  },

  section_speedrunner: {
    id: 'section_speedrunner',
    title: 'Section Speedrunner',
    titleMedievalEn: 'The Swift Wanderer',
    description: 'Navigated through all sections in under 30 seconds',
    descMedievalEn: 'Thou hast traversed all chambers with legendary swiftness',
    icon: '⚡',
    rarity: 'rare',
    category: 'explorer',
    secret: false,
    xp: 60,
  },

  // ── Interaction ───────────────────────────────────────────────
  chatted_with_oracle: {
    id: 'chatted_with_oracle',
    title: 'The Oracle Speaks',
    titleMedievalEn: 'Communion with the Oracle',
    description: 'Sent a message to the AI chatbot',
    descMedievalEn: 'Thou hast consulted the mystical Oracle',
    icon: '🔮',
    rarity: 'common',
    category: 'interaction',
    secret: false,
    xp: 20,
  },

  sent_contact: {
    id: 'sent_contact',
    title: 'The Raven Dispatched',
    titleMedievalEn: 'A Raven Takes Flight',
    description: 'Sent a message through the contact form',
    descMedievalEn: 'Thou hast dispatched a raven bearing thy message',
    icon: '🐦‍⬛',
    rarity: 'uncommon',
    category: 'interaction',
    secret: false,
    xp: 40,
  },

  copied_code: {
    id: 'copied_code',
    title: 'Code Thief',
    titleMedievalEn: 'The Scroll Transcriber',
    description: 'Copied a code snippet from a blog post',
    descMedievalEn: 'Thou hast copied arcane inscriptions from the scrolls',
    icon: '📋',
    rarity: 'common',
    category: 'interaction',
    secret: false,
    xp: 15,
  },

  opened_pdf: {
    id: 'opened_pdf',
    title: 'The Archivist',
    titleMedievalEn: 'Keeper of the Ancient Scrolls',
    description: 'Opened a PDF document',
    descMedievalEn: 'Thou hast unfurled an ancient scroll',
    icon: '📄',
    rarity: 'common',
    category: 'interaction',
    secret: false,
    xp: 15,
  },

  viewed_image: {
    id: 'viewed_image',
    title: 'The Observer',
    titleMedievalEn: 'Gazer of Visions',
    description: 'Opened the image viewer',
    descMedievalEn: 'Thou hast gazed upon an arcane vision',
    icon: '🖼️',
    rarity: 'common',
    category: 'interaction',
    secret: false,
    xp: 10,
  },

  changed_theme: {
    id: 'changed_theme',
    title: 'The Shapeshifter',
    titleMedievalEn: 'Weaver of Illusions',
    description: 'Changed the app theme',
    descMedievalEn: 'Thou hast reshaped the very fabric of the keep',
    icon: '🎨',
    rarity: 'common',
    category: 'interaction',
    secret: false,
    xp: 10,
  },

  tried_all_themes: {
    id: 'tried_all_themes',
    title: 'The Chromancer',
    titleMedievalEn: 'Master of All Illusions',
    description: 'Tried all available themes',
    descMedievalEn: 'Thou hast mastered every form of the enchanted keep',
    icon: '✨',
    rarity: 'rare',
    category: 'interaction',
    secret: false,
    xp: 50,
  },

  font_scholar: {
    id: 'font_scholar',
    title: 'Font Scholar',
    titleMedievalEn: 'Calligrapher of the Realm',
    description: 'Changed the font size in settings',
    descMedievalEn: 'Thou hast reshaped the sacred runes of typography',
    icon: '🔤',
    rarity: 'uncommon',
    category: 'interaction',
    secret: false,
    xp: 20,
  },

  motion_master: {
    id: 'motion_master',
    title: 'Motion Master',
    titleMedievalEn: 'Commander of the Winds',
    description: 'Toggled the reduced motion setting',
    descMedievalEn: 'Thou hast commanded the winds of motion to cease or flow',
    icon: '🌀',
    rarity: 'uncommon',
    category: 'interaction',
    secret: false,
    xp: 20,
  },

  language_weaver: {
    id: 'language_weaver',
    title: 'Language Weaver',
    titleMedievalEn: 'Polyglot of the Ancient Tongues',
    description: 'Switched between all available languages',
    descMedievalEn: 'Thou hast spoken in every tongue known to the realm',
    icon: '🌐',
    rarity: 'rare',
    category: 'interaction',
    secret: false,
    xp: 60,
  },

  scroll_collector: {
    id: 'scroll_collector',
    title: 'Scroll Collector',
    titleMedievalEn: 'Keeper of Bookmarks',
    description: 'Bookmarked 3 blog posts',
    descMedievalEn: 'Thou hast collected 3 sacred scrolls in thy satchel',
    icon: '🔖',
    rarity: 'uncommon',
    category: 'interaction',
    secret: false,
    xp: 30,
    requirement: { type: 'count', key: 'bookmarks', target: 3 },
  },

  keyboard_squire: {
    id: 'keyboard_squire',
    title: 'Keyboard Squire',
    titleMedievalEn: 'The Keystroke Apprentice',
    description: 'Used a keyboard shortcut',
    descMedievalEn: 'Thou hast invoked the sacred keystroke incantation',
    icon: '⌨️',
    rarity: 'uncommon',
    category: 'interaction',
    secret: false,
    xp: 20,
  },

  theme_alchemist: {
    id: 'theme_alchemist',
    title: 'Theme Alchemist',
    titleMedievalEn: 'Transmuter of Hues',
    description: 'Created a custom theme color scheme',
    descMedievalEn: 'Thou hast transmuted the raw essence of color into a new form',
    icon: '⚗️',
    rarity: 'rare',
    category: 'interaction',
    secret: false,
    xp: 50,
  },

  settings_tinkerer: {
    id: 'settings_tinkerer',
    title: 'Settings Tinkerer',
    titleMedievalEn: 'Master of the Configuration Tome',
    description: 'Changed at least 5 different settings',
    descMedievalEn: 'Thou hast rearranged the very foundations of the keep',
    icon: '🔧',
    rarity: 'uncommon',
    category: 'interaction',
    secret: false,
    xp: 30,
  },

  pdf_scholar: {
    id: 'pdf_scholar',
    title: 'PDF Scholar',
    titleMedievalEn: 'Reader of the Forbidden Scrolls',
    description: 'Opened 3 different PDF documents',
    descMedievalEn: 'Thou hast unfurled 3 ancient scrolls of forbidden knowledge',
    icon: '📑',
    rarity: 'uncommon',
    category: 'interaction',
    secret: false,
    xp: 30,
    requirement: { type: 'count', key: 'pdfs_opened', target: 3 },
  },

  // ── Reader ────────────────────────────────────────────────────
  read_blog_post: {
    id: 'read_blog_post',
    title: 'The Reader',
    titleMedievalEn: 'Student of the Scrolls',
    description: 'Read a blog post',
    descMedievalEn: 'Thou hast studied the arcane writings',
    icon: '📖',
    rarity: 'common',
    category: 'reader',
    secret: false,
    xp: 20,
  },

  read_5_blogs: {
    id: 'read_5_blogs',
    title: 'Bookworm',
    titleMedievalEn: 'The Devoted Scholar',
    description: 'Read 5 blog posts',
    descMedievalEn: 'Thou hast consumed 5 scrolls of arcane knowledge',
    icon: '📚',
    rarity: 'uncommon',
    category: 'reader',
    secret: false,
    xp: 60,
    requirement: { type: 'count', key: 'blogs_read', target: 5 },
  },

  page_turner: {
    id: 'page_turner',
    title: 'Page Turner',
    titleMedievalEn: 'The Avid Reader',
    description: 'Read 3 blog posts',
    descMedievalEn: 'Thou hast turned 3 pages of the sacred chronicles',
    icon: '📃',
    rarity: 'uncommon',
    category: 'reader',
    secret: false,
    xp: 40,
    requirement: { type: 'count', key: 'blogs_read', target: 3 },
  },

  lore_master: {
    id: 'lore_master',
    title: 'Lore Master',
    titleMedievalEn: 'Keeper of All Knowledge',
    description: 'Read every blog post in the portfolio',
    descMedievalEn: 'Thou hast consumed every scroll in the grand library',
    icon: '🧠',
    rarity: 'rare',
    category: 'reader',
    secret: false,
    xp: 100,
  },

  speed_reader: {
    id: 'speed_reader',
    title: 'Speed Reader',
    titleMedievalEn: 'The Swift Scholar',
    description: 'Finished a blog post in under 2 minutes',
    descMedievalEn: 'Thou hast devoured a scroll with supernatural speed',
    icon: '💨',
    rarity: 'rare',
    category: 'reader',
    secret: false,
    xp: 40,
  },

  studious_apprentice: {
    id: 'studious_apprentice',
    title: 'Studious Apprentice',
    titleMedievalEn: 'Dedicated to the Order',
    description: 'Read all modules in one semester',
    descMedievalEn: 'Thou hast studied every tome in a single semester',
    icon: '📋',
    rarity: 'uncommon',
    category: 'reader',
    secret: false,
    xp: 50,
  },

  academic_scholar: {
    id: 'academic_scholar',
    title: 'Academic Scholar',
    titleMedievalEn: 'Grand Scholar of the Order',
    description: 'Read all modules across both semesters',
    descMedievalEn: 'Thou hast mastered every tome across both great campaigns',
    icon: '🎓',
    rarity: 'epic',
    category: 'reader',
    secret: false,
    xp: 100,
  },

  // ── Secret / Hidden ───────────────────────────────────────────
  night_owl: {
    id: 'night_owl',
    title: 'Night Owl',
    titleMedievalEn: 'The Midnight Sorcerer',
    description: 'Visited between midnight and 4am',
    descMedievalEn: 'Thou hast wandered the keep in the darkest hour',
    icon: '🦉',
    rarity: 'rare',
    category: 'secret',
    secret: true,
    xp: 50,
  },

  konami_code: {
    id: 'konami_code',
    title: 'Cheat Code Activated',
    titleMedievalEn: 'The Ancient Sequence',
    description: 'Entered the Konami code',
    descMedievalEn: 'Thou hast spoken the ancient sequence of power',
    icon: '🎮',
    rarity: 'epic',
    category: 'secret',
    secret: true,
    xp: 100,
  },

  idle_wanderer: {
    id: 'idle_wanderer',
    title: 'The Wanderer',
    titleMedievalEn: 'Lost in the Keep',
    description: 'Stayed on the page for over 5 minutes',
    descMedievalEn: 'Thou hast lingered within the keep for an age',
    icon: '⏳',
    rarity: 'uncommon',
    category: 'secret',
    secret: true,
    xp: 30,
  },

  rapid_clicker: {
    id: 'rapid_clicker',
    title: 'Trigger Happy',
    titleMedievalEn: 'The Frenzied Warrior',
    description: 'Clicked something 10 times rapidly',
    descMedievalEn: 'Thou hast struck with unrestrained fury',
    icon: '⚡',
    rarity: 'rare',
    category: 'secret',
    secret: true,
    xp: 40,
  },

  triple_click: {
    id: 'triple_click',
    title: 'Triple Click',
    titleMedievalEn: 'The Triple Strike',
    description: 'Triple-clicked anywhere on the page',
    descMedievalEn: 'Thou hast delivered three swift strikes to the parchment',
    icon: '🖱️',
    rarity: 'rare',
    category: 'secret',
    secret: true,
    xp: 30,
  },

  scroll_master: {
    id: 'scroll_master',
    title: 'Scroll Master',
    titleMedievalEn: 'The Keyboard Wanderer',
    description: 'Scrolled using only the keyboard for 30 seconds',
    descMedievalEn: 'Thou hast navigated the scrolls by keystroke alone',
    icon: '⌨️',
    rarity: 'uncommon',
    category: 'secret',
    secret: true,
    xp: 25,
  },

  console_explorer: {
    id: 'console_explorer',
    title: 'Console Explorer',
    titleMedievalEn: 'Peeker Behind the Veil',
    description: 'Opened the browser console',
    descMedievalEn: 'Thou hast gazed behind the arcane veil of the keep',
    icon: '💻',
    rarity: 'epic',
    category: 'secret',
    secret: true,
    xp: 80,
  },

  mobile_warrior: {
    id: 'mobile_warrior',
    title: 'Mobile Warrior',
    titleMedievalEn: 'Champion of the Small Screen',
    description: 'Used the portfolio on a mobile device',
    descMedievalEn: 'Thou hast proven thy valor on the smallest of screens',
    icon: '📱',
    rarity: 'uncommon',
    category: 'secret',
    secret: true,
    xp: 20,
  },

  back_button_hero: {
    id: 'back_button_hero',
    title: 'Back Button Hero',
    titleMedievalEn: 'The Time Wanderer',
    description: 'Used the browser back button 5 times in one session',
    descMedievalEn: 'Thou hast retraced thy steps through five ancient portals',
    icon: '🔙',
    rarity: 'uncommon',
    category: 'secret',
    secret: true,
    xp: 25,
    requirement: { type: 'count', key: 'back_button', target: 5 },
  },

  right_click_rebel: {
    id: 'right_click_rebel',
    title: 'Right-Click Rebel',
    titleMedievalEn: 'Defier of the Standard Order',
    description: 'Used the custom context menu 3 times',
    descMedievalEn: 'Thou hast invoked the forbidden context menu three times',
    icon: '🏴',
    rarity: 'rare',
    category: 'secret',
    secret: true,
    xp: 35,
    requirement: { type: 'count', key: 'context_menu_used', target: 3 },
  },

  tab_switcher: {
    id: 'tab_switcher',
    title: 'Tab Switcher',
    titleMedievalEn: 'The Portal Hopper',
    description: 'Switched browser tabs and returned within 5 seconds',
    descMedievalEn: 'Thou hast stepped through the portal and returned swiftly',
    icon: '🔀',
    rarity: 'rare',
    category: 'secret',
    secret: true,
    xp: 25,
  },

  pixel_perfect: {
    id: 'pixel_perfect',
    title: 'Pixel Perfect',
    titleMedievalEn: 'The Destined Resolution',
    description: 'Visited the portfolio on exactly 1920x1080 resolution',
    descMedievalEn: 'The stars aligned to grant thee the perfect vision',
    icon: '🎯',
    rarity: 'legendary',
    category: 'secret',
    secret: true,
    xp: 150,
  },

  the_cartographer: {
    id: 'the_cartographer',
    title: 'The Cartographer',
    titleMedievalEn: 'Mapmaker of the Keep',
    description: 'Clicked every navigation link in the header in one session',
    descMedievalEn: 'Thou hast traced every path marked on the ancient map',
    icon: '🧭',
    rarity: 'epic',
    category: 'secret',
    secret: true,
    xp: 80,
  },

  easter_egg_hunter: {
    id: 'easter_egg_hunter',
    title: 'Easter Egg Hunter',
    titleMedievalEn: 'Finder of Hidden Relics',
    description: 'Found 3 hidden easter eggs across the site',
    descMedievalEn: 'Thou hast unearthed 3 relics hidden within the keep',
    icon: '🥚',
    rarity: 'legendary',
    category: 'secret',
    secret: true,
    xp: 200,
    requirement: { type: 'count', key: 'easter_eggs_found', target: 3 },
  },

  // ── Loyalty ───────────────────────────────────────────────────
  returning_visitor: {
    id: 'returning_visitor',
    title: 'Returning Knight',
    titleMedievalEn: 'The Loyal Knight',
    description: 'Visited the portfolio a second time',
    descMedievalEn: 'Thou hast returned to the enchanted keep once more',
    icon: '🛡️',
    rarity: 'uncommon',
    category: 'loyalty',
    secret: false,
    xp: 25,
  },

  five_visits: {
    id: 'five_visits',
    title: 'Regular',
    titleMedievalEn: 'Champion of the Keep',
    description: 'Visited the portfolio 5 times',
    descMedievalEn: 'Thou art a true champion of this enchanted domain',
    icon: '👑',
    rarity: 'epic',
    category: 'loyalty',
    secret: false,
    xp: 100,
    requirement: { type: 'count', key: 'visit_count', target: 5 },
  },

  ten_visits: {
    id: 'ten_visits',
    title: 'Veteran Visitor',
    titleMedievalEn: 'Guardian of the Gate',
    description: 'Visited the portfolio 10 times',
    descMedievalEn: 'Thou hast crossed the gates ten times, true guardian',
    icon: '🏰',
    rarity: 'epic',
    category: 'loyalty',
    secret: false,
    xp: 120,
    requirement: { type: 'count', key: 'visit_count', target: 10 },
  },

  monthly_knight: {
    id: 'monthly_knight',
    title: 'Monthly Knight',
    titleMedievalEn: 'Sentinel of the Calendar',
    description: 'Visited on 5 different days in one month',
    descMedievalEn: 'Thou hast kept vigil across five moons of a single cycle',
    icon: '🗓️',
    rarity: 'legendary',
    category: 'loyalty',
    secret: false,
    xp: 200,
  },

  dedicated_scholar: {
    id: 'dedicated_scholar',
    title: 'Dedicated Scholar',
    titleMedievalEn: 'The Persistent Reader',
    description: 'Read a blog post 3 times',
    descMedievalEn: 'Thou hast returned to study the same scroll thrice',
    icon: '🔍',
    rarity: 'rare',
    category: 'loyalty',
    secret: false,
    xp: 40,
  },

  first_to_follow: {
    id: 'first_to_follow',
    title: 'First to Follow',
    titleMedievalEn: 'The Loyal Pathfinder',
    description: 'Followed a blog series from first to last post',
    descMedievalEn: 'Thou hast followed the sacred chronicles from start to end',
    icon: '📖',
    rarity: 'uncommon',
    category: 'loyalty',
    secret: false,
    xp: 50,
  },

  seasoned_veteran: {
    id: 'seasoned_veteran',
    title: 'Seasoned Veteran',
    titleMedievalEn: 'Eternal Sentinel',
    description: 'Visited the portfolio 25 times',
    descMedievalEn: 'Thou art an eternal sentinel of the enchanted keep',
    icon: '⚜️',
    rarity: 'legendary',
    category: 'loyalty',
    secret: false,
    xp: 300,
    requirement: { type: 'count', key: 'visit_count', target: 25 },
  },

  // ── Academic (CRMEF specific) ────────────────────────────────
  semester_graduate: {
    id: 'semester_graduate',
    title: 'Semester Graduate',
    titleMedievalEn: 'Campaign Completer',
    description: 'Viewed all modules in one semester',
    descMedievalEn: 'Thou hast completed the study of a full campaign',
    icon: '📜',
    rarity: 'uncommon',
    category: 'academic',
    secret: false,
    xp: 40,
  },

  full_graduate: {
    id: 'full_graduate',
    title: 'Full Graduate',
    titleMedievalEn: 'Grand Graduate of the Order',
    description: 'Viewed all modules across both semesters',
    descMedievalEn: 'Thou hast mastered both great campaigns of the Order',
    icon: '🎓',
    rarity: 'rare',
    category: 'academic',
    secret: false,
    xp: 80,
  },

  document_collector: {
    id: 'document_collector',
    title: 'Document Collector',
    titleMedievalEn: 'Archivist of the Order',
    description: 'Opened 10 different CRMEF documents',
    descMedievalEn: 'Thou hast collected 10 sacred documents from the archives',
    icon: '📚',
    rarity: 'rare',
    category: 'academic',
    secret: false,
    xp: 60,
    requirement: { type: 'count', key: 'crmef_docs_opened', target: 10 },
  },

  video_scholar: {
    id: 'video_scholar',
    title: 'Video Scholar',
    titleMedievalEn: 'Watcher of the Scrying Pool',
    description: 'Watched a learning video',
    descMedievalEn: 'Thou hast gazed into the scrying pool of knowledge',
    icon: '🎬',
    rarity: 'uncommon',
    category: 'academic',
    secret: false,
    xp: 25,
  },

  msp_explorer: {
    id: 'msp_explorer',
    title: 'MSP Explorer',
    titleMedievalEn: 'Chronicler of the Internship',
    description: 'Read through the MSP internship report',
    descMedievalEn: 'Thou hast studied the great chronicle of the MSP campaign',
    icon: '📋',
    rarity: 'uncommon',
    category: 'academic',
    secret: false,
    xp: 30,
  },

  // ── Gamification ──────────────────────────────────────────────
  first_achievement: {
    id: 'first_achievement',
    title: 'First Achievement',
    titleMedievalEn: 'The First Trophy',
    description: 'Unlocked your first achievement',
    descMedievalEn: 'Thou hast claimed thy first trophy from the vault',
    icon: '🏆',
    rarity: 'common',
    category: 'gamification',
    secret: false,
    xp: 5,
  },

  achievement_collector: {
    id: 'achievement_collector',
    title: 'Achievement Collector',
    titleMedievalEn: 'Gatherer of Trophies',
    description: 'Unlocked 10 achievements',
    descMedievalEn: 'Thou hast gathered 10 trophies in thy collection',
    icon: '🏅',
    rarity: 'uncommon',
    category: 'gamification',
    secret: false,
    xp: 50,
    requirement: { type: 'count', key: 'achievements_unlocked', target: 10 },
  },

  achievement_hunter: {
    id: 'achievement_hunter',
    title: 'Achievement Hunter',
    titleMedievalEn: 'The Relentless Seeker',
    description: 'Unlocked 20 achievements',
    descMedievalEn: 'Thou hast hunted down 20 trophies across the realm',
    icon: '🎖️',
    rarity: 'rare',
    category: 'gamification',
    secret: false,
    xp: 100,
    requirement: { type: 'count', key: 'achievements_unlocked', target: 20 },
  },

  completionist: {
    id: 'completionist',
    title: 'Completionist',
    titleMedievalEn: 'Master of All Trophies',
    description: 'Unlocked all achievements',
    descMedievalEn: 'Thou hast claimed every trophy in the grand vault',
    icon: '💎',
    rarity: 'legendary',
    category: 'gamification',
    secret: false,
    xp: 500,
  },

  xp_hoarder: {
    id: 'xp_hoarder',
    title: 'XP Hoarder',
    titleMedievalEn: 'Collector of Experience Orbs',
    description: 'Accumulated 500 total XP',
    descMedievalEn: 'Thou hast hoarded 500 orbs of raw experience',
    icon: '🟣',
    rarity: 'epic',
    category: 'gamification',
    secret: false,
    xp: 0,
  },

  xp_legend: {
    id: 'xp_legend',
    title: 'XP Legend',
    titleMedievalEn: 'The Enlightened One',
    description: 'Accumulated 1000 total XP',
    descMedievalEn: 'Thou hast achieved 1000 orbs of transcendent wisdom',
    icon: '🌟',
    rarity: 'legendary',
    category: 'gamification',
    secret: false,
    xp: 0,
  },

};

export const ACHIEVEMENT_CATEGORIES = {
  explorer: { label: 'Explorer', icon: '🗺️' },
  interaction: { label: 'Interaction', icon: '⚡' },
  reader: { label: 'Reader', icon: '📖' },
  secret: { label: 'Secret', icon: '🔮' },
  loyalty: { label: 'Loyalty', icon: '🛡️' },
  academic: { label: 'Academic', icon: '🎓' },
  gamification: { label: 'Gamification', icon: '🏆' },
};

export const RARITY_CONFIG = {
  common:    { label: 'Common',    color: '#94a3b8', glow: 'rgba(148,163,184,0.4)' },
  uncommon:  { label: 'Uncommon',  color: '#4ade80', glow: 'rgba(74,222,128,0.4)' },
  rare:      { label: 'Rare',      color: '#60a5fa', glow: 'rgba(96,165,250,0.4)' },
  epic:      { label: 'Epic',      color: '#c084fc', glow: 'rgba(192,132,252,0.4)' },
  legendary: { label: 'Legendary', color: '#fbbf24', glow: 'rgba(251,191,36,0.5)' },
};
